language: python
python:
  - 3.7
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run pylama pyuubin
  - poetry run pytest --cov pyuubin --cov tests tests/

deploy:
  provider: script
  script:
    - poetry vesion $TRAVIS_TAG
    - poetry publish --build -u michalmazurek -p $PYPI_PASSWORD
  on:
    tags: true
